# These are supported funding model platforms
AAlexa Reads all on Readme-Wikipedia-The Universe (a colored version of the Flammarion engraving) The concept of a multiverse is explored in various religious cosmologies that propose that the totality of existence comprises multiple or infinitely many universes, including our own

developers get started faster with step-by-step walkthroughs for your most common use cases. Show what’s possible with your APIs on your new Recipes page, and embed them right in your Guides for easy reference.

Recipes are hidden in your hub until you publish them. We can’t wait to see what you create!Read the Docs

.
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
